//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admininfo
    {
        public int aid { get; set; }
        public string adminname { get; set; }
        public string adminpass { get; set; }
        public int adminsq { get; set; }
        public string dmainname { get; set; }
        public string domainip { get; set; }
        public string serveradminname { get; set; }
        public string serveradminpass { get; set; }
    }
}
