//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userinfo
    {
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<int> adminq { get; set; }
        public string ansforaq { get; set; }
        public Nullable<int> userq { get; set; }
        public string ansforuq { get; set; }
        public int uid { get; set; }
        public string passwordsalt { get; set; }
        public Nullable<bool> AdminApproved { get; set; }
        public int failurecount { get; set; }
    }
}
