//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class useraudit
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> paswordchangedate { get; set; }
        public string ipaddress { get; set; }
    }
}
